// This file is part of HugoChecker - A GitHub Action to check Hugo markdown files.
// Copyright (c) Krzysztof Prusik and contributors
// https://github.com/marketplace/actions/hugochecker
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System.Collections.Generic;
using System.Globalization;

namespace HugoChecker.Extensions;

public static class StringExtensions
{
    private static readonly Dictionary<string, string> cultureMap = new()
    {
        { "af", "af-ZA" },
        { "ak", "ak-GH" },
        { "sq", "sq-AL" },
        { "am", "am-ET" },
        { "ar", "ar-SA" },
        { "an", "an-ES" },
        { "hy", "hy-AM" },
        { "as", "as-IN" },
        { "av", "av-RU" },
        { "ae", "ae-AE" },
        { "ay", "ay-BO" },
        { "az", "az-AZ" },
        { "ba", "ba-RU" },
        { "eu", "eu-ES" },
        { "be", "be-BY" },
        { "bn", "bn-BD" },
        { "bh", "bh-IN" },
        { "bi", "bi-VU" },
        { "bs", "bs-BA" },
        { "br", "br-FR" },
        { "bg", "bg-BG" },
        { "my", "my-MM" },
        { "ca", "ca-ES" },
        { "ch", "ch-GU" },
        { "ce", "ce-RU" },
        { "ny", "ny-MW" },
        { "zh", "zh-CN" },
        { "cu", "cu-RU" },
        { "cv", "cv-RU" },
        { "kw", "kw-GB" },
        { "co", "co-FR" },
        { "cr", "cr-CA" },
        { "hr", "hr-HR" },
        { "cs", "cs-CZ" },
        { "da", "da-DK" },
        { "dv", "dv-MV" },
        { "dz", "dz-BT" },
        { "en", "en-US" },
        { "eo", "eo-EO" },
        { "et", "et-EE" },
        { "ee", "ee-GH" },
        { "fo", "fo-FO" },
        { "fj", "fj-FJ" },
        { "fi", "fi-FI" },
        { "fr", "fr-FR" },
        { "fy", "fy-NL" },
        { "gl", "gl-ES" },
        { "ka", "ka-GE" },
        { "de", "de-DE" },
        { "el", "el-GR" },
        { "gn", "gn-PY" },
        { "gu", "gu-IN" },
        { "ht", "ht-HT" },
        { "ha", "ha-NG" },
        { "he", "he-IL" },
        { "her", "her-NA" },
        { "hi", "hi-IN" },
        { "ho", "ho-PG" },
        { "hu", "hu-HU" },
        { "is", "is-IS" },
        { "io", "io-IO" },
        { "ig", "ig-NG" },
        { "id", "id-ID" },
        { "ia", "ia-IA" },
        { "ie", "ie-IE" },
        { "iu", "iu-CA" },
        { "ik", "ik-CA" },
        { "ga", "ga-IE" },
        { "it", "it-IT" },
        { "ja", "ja-JP" },
        { "jv", "jv-ID" },
        { "kl", "kl-GL" },
        { "kn", "kn-IN" },
        { "kr", "kr-NG" },
        { "ks", "ks-IN" },
        { "kk", "kk-KZ" },
        { "km", "km-KH" },
        { "ki", "ki-KE" },
        { "rw", "rw-RW" },
        { "ky", "ky-KG" },
        { "kv", "kv-RU" },
        { "kg", "kg-CD" },
        { "ko", "ko-KR" },
        { "ku", "ku-TR" },
        { "kj", "kj-NA" },
        { "la", "la-VA" },
        { "lb", "lb-LU" },
        { "gv", "gv-IM" },
        { "mk", "mk-MK" },
        { "mg", "mg-MG" },
        { "ms", "ms-MY" },
        { "ml", "ml-IN" },
        { "mr", "mr-IN" },
        { "mo", "mo-MD" },
        { "mn", "mn-MN" },
        { "na", "na-NR" },
        { "nv", "nv-US" },
        { "nd", "nd-ZW" },
        { "ne", "ne-NP" },
        { "ng", "ng-NE" },
        { "nl", "nl-NL" },
        { "no", "no-NO" },
        { "oj", "oj-CA" },
        { "or", "or-IN" },
        { "om", "om-ET" },
        { "os", "os-RU" },
        { "pa", "pa-IN" },
        { "fa", "fa-IR" },
        { "pl", "pl-PL" },
        { "ps", "ps-AF" },
        { "pt", "pt-PT" },
        { "qu", "qu-PE" },
        { "ro", "ro-RO" },
        { "rm", "rm-CH" },
        { "ru", "ru-RU" },
        { "se", "se-NO" },
        { "sm", "sm-WS" },
        { "sg", "sg-CF" },
        { "sr", "sr-RS" },
        { "gd", "gd-GB" },
        { "sn", "sn-ZW" },
        { "sd", "sd-PK" },
        { "si", "si-LK" },
        { "sk", "sk-SK" },
        { "sl", "sl-SI" },
        { "so", "so-SO" },
        { "st", "st-LS" },
        { "nr", "nr-ZA" },
        { "es", "es-ES" },
        { "su", "su-ID" },
        { "sw", "sw-TZ" },
        { "ss", "ss-SZ" },
        { "sv", "sv-SE" },
        { "ta", "ta-IN" },
        { "te", "te-IN" },
        { "tg", "tg-TJ" },
        { "th", "th-TH" },
        { "ti", "ti-ET" },
        { "bo", "bo-CN" },
        { "tk", "tk-TM" },
        { "tl", "tl-PH" },
        { "tn", "tn-BW" },
        { "to", "to-TO" },
        { "tr", "tr-TR" },
        { "ts", "ts-ZA" },
        { "tt", "tt-RU" },
        { "tw", "tw-GH" },
        { "ty", "ty-PF" },
        { "ug", "ug-CN" },
        { "uk", "uk-UA" },
        { "ur", "ur-PK" },
        { "uz", "uz-UZ" },
        { "ve", "ve-ZA" },
        { "vi", "vi-VN" },
        { "vo", "vo-VU" },
        { "wa", "wa-BE" },
        { "cy", "cy-GB" },
        { "wo", "wo-SN" },
        { "xh", "xh-ZA" },
        { "yi", "yi-US" },
        { "yo", "yo-NG" },
        { "za", "za-CN" },
        { "zu", "zu-ZA" }
    };
    
    public static CultureInfo FindCulture(this string languageCode) => 
        cultureMap.ContainsKey(languageCode) ? new CultureInfo(cultureMap[languageCode]) : new CultureInfo(languageCode);
}